### ISSUE TITLE
[Docs]The updation of shields is needed in README.md

### ISSUE THREAD

**Issue by Swapnil-Bhabal** [meshery/meshery-cilium#11]
**Current State:**
Small updation of shields in README.md

![image](https://user-images.githubusercontent.com/61308713/146511791-185752ee-3e9e-4521-b604-c330a28c55e0.png)

**Desired State:**
This is how it should look like: 

![image](https://user-images.githubusercontent.com/61308713/146511829-24a9db5f-1559-4d9b-85ed-2deefdb12258.png)

updation should be done in this README.md by keeping the shield style uniform to following meshery-istio's README.md :
https://github.com/meshery/meshery-istio/blob/721b78783182e65145cefde64d905dab3ca20ba1/README.md?plain=1#L13

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Swapnil-Bhabal** [comment]
Kindly assign this issue to me

**Comment by Abhijay007** [comment]
> Kindly assign this issue to me

@Swapnil-Bhabal I think currently we don't have "go report" and "build status" for CSM ( Cilium service mesh ) project.

**Comment by Swapnil-Bhabal** [comment]
Okay @Abhijay007 i will remove it and add it again if it is fine ?

**Comment by Abhijay007** [comment]
> Okay @Abhijay007 i will remove it and add it again if it is fine ?

you can ask @warunicorn19 @YashKamboj, maybe they can help, as I don't have much idea about the go report and build status of Cilium service mesh project  :)

**Comment by Swapnil-Bhabal** [comment]
Okay @Abhijay007, Actually to add more context 
this updation was proposed by lee calcote sir, he wanted the shield section to be same as the shield of meshery-istio in every repositories README.

Being a new comer i took up this task and i am raising issues from every repository.

Updations of few repositories will be done by me, and the remaining links i am planning to post in community new comers channel so it serve as first contribution to every new comers as well.

**Comment by Abhijay007** [comment]
> Okay @Abhijay007, Actually to add more context this updation was proposed by lee calcote sir, he wanted the shield section to be same as the shield of meshery-istio in every repositories README.
> 
> Being a new comer i took up this task and i am raising issues from every repository.
> 
> Updations of few repositories will be done by me, and the remaining links i am planning to post in community new comers channel so it serve as first contribution to every new comers as well.

Oh, that's great !! let me know if you need any assistance, I  am currently contributing to layer5.io ( official site ), Mesheary site, Meshery-cilium, Meshery-osm and planning to contribute on nighthawk as well, I am also a newcomer, let me know if you want any assistance regarding setting up / running projects in locally, I will try my best to assist and welcome to the community : )

**Comment by Swapnil-Bhabal** [comment]
Thank you so much @Abhijay007 
I might need assistance in setting up the project on my local system soon i will reach out to you on slack.

**Comment by Abhijay007** [comment]
> Thank you so much @Abhijay007 I might need assistance in setting up the project on my local system soon i will reach out to you on slack.

sure :)

**Comment by leecalcote** [comment]
Done?
