### ISSUE TITLE
[chore] update Go to 1.21, and update relevant pkgs

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery-cilium#144]
### Desired Behaviour
Need to update `Go` to `1.21` in `go.mod` and in `Dockerfile`, and also `Makefile`

- Minor chore on updating `meshkit` and `meshery-adapter-library`

**Comment by kapooraryan** [comment]
Can this be assigned to me if open @Ghat0tkach @saurabh100ni ?

**Comment by hemantmm** [comment]
@saurabh100ni would like to work on this issue.
