### ISSUE TITLE
Build Failure: ServiceMesh_CILIUM_SERVICE_MESH not declared by package smp (typecheck)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-cilium#19]
#### Current Behavior
```
➜  meshery-cilium git:(master) make
golangci-lint run
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
internal/config/config.go:24:19: ServiceMesh_CILIUM_SERVICE_MESH not declared by package smp (typecheck)
		"name":     smp.ServiceMesh_CILIUM_SERVICE_MESH.Enum().String(),
		                ^
internal/config/config.go:31:18: ServiceMesh_CILIUM_SERVICE_MESH not declared by package smp (typecheck)
		"name":    smp.ServiceMesh_CILIUM_SERVICE_MESH.Enum().String(),
		               ^
internal/config/operations.go:10:40: ServiceMesh_CILIUM_SERVICE_MESH not declared by package smp (typecheck)
	CiliumOperation = strings.ToLower(smp.ServiceMesh_CILIUM_SERVICE_MESH.Enum().String())
	                                      ^
make: *** [check] Error 1
```

#### Expected Behavior
Adapter should build and run.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by iamsdas** [comment]
@leecalcote  SMP needs a new release to reflect the latest changes. After that, we just have to update its package version in this repo.

**Comment by leecalcote** [comment]
@iamsdas, let's do it.

@gyohuangxin ready to make a Service Mesh Performance release?

**Comment by gyohuangxin** [comment]
@leecalcote Yes. But can you review this [PR](https://github.com/service-mesh-performance/service-mesh-performance/pull/296) which was pending for a while. I think it will be useful if we implement it in the new release.

**Comment by navendu-pottekkat** [comment]
@gyohuangxin We can merge your PR and make a new release.

**Comment by gyohuangxin** [comment]
@navendu-pottekkat Thank you!

**Comment by leecalcote** [comment]
@iamsdas has the new SMP release been incorporated into this adapter?

**Comment by leecalcote** [comment]
Fixed
