### ISSUE TITLE
problem with helm installation 

### ISSUE THREAD

**Issue by Shreyas220** [meshery/meshery-cilium#21]
#### Current Behavior
Currently, we install Cilium using helm, but we often face problems while installing.

#### Expected Behavior
Install Cilium directly from the latest release https://github.com/cilium/cilium-cli/releases/tag/v0.10.2

#### Screenshots/Logs

```

kubectl get pods -A
NAMESPACE              NAME                                         READY   STATUS              RESTARTS      AGE
kube-system            cilium-operator-5986db558f-p57xs             0/1     Pending             0             17s
kube-system            cilium-operator-5986db558f-z4qgv             1/1     Running             0             17s
kube-system            cilium-tnv46                                 0/1     Error               1 (9s ago)    17s
```

**Comment by Shreyas220** [comment]
@leecalcote apparently there is some problem when installing it using helm

**Comment by leecalcote** [comment]
@hershd23, will you have a look at this?

// @Revolyssup @piyushsingariya

**Comment by leecalcote** [comment]
@Shreyas220 is this an issue with your environment, with Cilium or with the adapter?

**Comment by hershd23** [comment]
Yes, I'll take a look at it

**Comment by Shreyas220** [comment]
> @Shreyas220 is this an issue with your environment, with Cilium or with the adapter? Share adapter logs, please.

my bad I should have stated this in the issue 
The problem is with Cilium while using helm, not with the adapter 
The log mentioned above is when installing it directly through helm (not using the adapter), i did mention this in slack once [here](https://layer5io.slack.com/archives/C017NA80S66/p1642066904023400)
suryashankar and i both have faced this so this might not be a problem with my environment 
@hershd23  could also test it once just to be sure

**Comment by leecalcote** [comment]
Gents, checking in here in case there's progress to report...

**Comment by hershd23** [comment]
Nope @leecalcote, completely forgot about this

@Shreyas220 can you paste what you did and the logs again, not able to view your messages. Can you rather add that to the discuss forum and share the link because I guess Slack will start deleting earlier messages now.

https://discuss.layer5.io/

**Comment by hershd23** [comment]
I tried to reproduce this but I am unable to do so

OS :- MacOS Big Sur 11.6

```
cilium-test   client-6488dcf5d4-5kggz             1/1     Running   0             7m9s
cilium-test   client2-5998d566b4-hpjtx            1/1     Running   0             7m9s
cilium-test   echo-same-node-745bd5c77-lq94k      1/1     Running   0             7m9s
kube-system   cilium-operator-6d8799bcbb-45kqc    1/1     Running   0             19m
kube-system   cilium-operator-6d8799bcbb-cdmlm    0/1     Pending   0             19m
kube-system   cilium-tnzc9                        1/1     Running   0             19m
```

```
cilium status --wait


    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       1 errors, 1 warnings
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 1, Ready: 1/1, Available: 1/1
Deployment        cilium-operator    Desired: 2, Ready: 1/2, Available: 1/2, Unavailable: 1/2
Containers:       cilium             Running: 1
                  cilium-operator    Running: 1, Pending: 1
Cluster Pods:     0/9 managed by Cilium
Image versions    cilium-operator    quay.io/cilium/operator-generic:v1.11.2@sha256:4c8bea6818ee3e4932f99e9c1d7efa88b8c0f3cd516160caec878406531e45e7: 2
                  cilium             quay.io/cilium/cilium:v1.11.2@sha256:4332428fbb528bda32fffe124454458c9b716c86211266d1a03c4ddf695d7f60: 1
Errors:           cilium-operator    cilium-operator                     1 pods of Deployment cilium-operator are not ready
Warnings:         cilium-operator    cilium-operator-6d8799bcbb-cdmlm    pod is pending
```

Although it says that there is an error here but actually given this is a single node cluster, only one operator is created the other is not as specified here https://github.com/rancher/rke2/issues/933 . 

Here is the connectivity test as well 

```
cilium connectivity test
ℹ️  Single-node environment detected, enabling single-node connectivity test
ℹ️  Monitor aggregation detected, will skip some flow validation steps
✨ [minikube] Creating namespace for connectivity check...
✨ [minikube] Deploying echo-same-node service...
✨ [minikube] Deploying same-node deployment...
✨ [minikube] Deploying client deployment...
✨ [minikube] Deploying client2 deployment...
⌛ [minikube] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [minikube] Waiting for deployments [] to become ready...
⌛ [minikube] Waiting for CiliumEndpoint for pod cilium-test/client-6488dcf5d4-5kggz to appear...

ℹ️  Cilium version: 1.11.2
🏃 Running tests...

[=] Test [no-policies]

[=] Test [allow-all-except-world]

[=] Test [client-ingress]

[=] Test [echo-ingress]

[=] Test [client-egress]

[=] Test [to-entities-world]

[=] Test [to-cidr-1111]

[=] Test [echo-ingress-l7]

[=] Test [client-egress-l7]

[=] Test [dns-only]

[=] Test [to-fqdns]

✅ All 11 tests (0 actions) successful, 0 tests skipped, 0 scenarios skipped.
```

**Comment by hershd23** [comment]
@Shreyas220 if you are using a linux system I can test on the one of the CIL machines as well to see if this issue occurs in Linux. But it would be really helpful if you can post the specifics of your machine and the error trace either here or in discuss forum, because AFAIK we might have lost your earlier message on the Slack channel due to the constraints of the free version :/

**Comment by jtaleric** [comment]
https://github.com/cilium/cilium-service-mesh-beta/pull/15 Might be relevant to the convo here.

**Comment by leecalcote** [comment]
@jtaleric thank you much. Yes, indeed. // @theBeginner86 @MUzairS15
