### ISSUE TITLE
[Patterns] Dynamic Component Generation: 7

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-cilium#23]
#### Current Behavior
7 total Cilium custom resources (seem) to exist today: https://doc.crds.dev/github.com/cilium/cilium

#### Desired Behavior
Each of these need to be supported by the Meshery Adapter for Cilium.

#### Implementation
See [Meshery Adapter Status Tracker](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit#gid=0) and [Meshery Adapters Design Spec](https://docs.google.com/document/d/1b8JAMzr3Rntu7CudRaYv6r6ccACJONAB5t7ISCaPNuA/edit#)

#### Acceptance Tests
All 7 components supported.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
@leecalcote Can I try on this?

**Comment by leecalcote** [comment]
@MUzairS15 that’d be great. Engage with @theBeginner86 as you go. He may have started down this path already.
