### ISSUE TITLE
Update GitHub Issue Templates

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-cilium#3]
#### Current Behavior
This GitHub [issue templates in this repo](https://github.com/meshery/meshery-cilium/tree/master/.github/ISSUE_TEMPLATE) are stale and need to be refreshed from those found in https://github.com/meshery/meshery-istio/tree/master/.github/ISSUE_TEMPLATE

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Abhijay007** [comment]
I wanna contribute to this issue, please assign me this issue @Mr-DG-Wick

**Comment by leecalcote** [comment]
Sounds great, @Abhijay007
