### ISSUE TITLE
[Chore] Refactor Cilium Operations

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery-cilium#30]
#### Current Behavior

- We have two operations.go file inside of cilium repo. 
- [meshery-cilium/cilium/operations.go](https://github.com/meshery/meshery-cilium/blob/master/cilium/operations.go) is redundant 

#### Expected Behavior

- Its functionalities should be moved to [meshery-cilium/cilium/cilium.go](https://github.com/meshery/meshery-cilium/blob/master/cilium/cilium.go). So that we maintain consistency across all meshery adapters.
- Correspondingly, other references to it must be updated.

For reference:
Check other meshery adapters, like: [meshery-istio](https://github.com/meshery/meshery-istio), [meshery-linkerd](https://github.com/meshery/meshery-linkerd) etc.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
@MUzairS15 would you like to work on this?

**Comment by MUzairS15** [comment]
Yes, sure @theBeginner86
