### ISSUE TITLE
[CI]Add end-to-end tests using service-mesh-pattern file.

### ISSUE THREAD

**Issue by Zanda256** [meshery/meshery-cilium#35]
#### Current Behavior
Currently e2e tests in the adapter only run tests for vanilla service mesh installation and for addons.

#### Desired Behavior
The link below is of an example pattern file that should also be deployed and assertions should be made.
https://github.com/service-mesh-patterns/service-mesh-patterns/blob/master/samples/minimalistiobookinfo.yaml

#### Reference:

- [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)

**Comment by Zanda256** [comment]
@MUzairS15 what's the blocker here?

**Comment by MUzairS15** [comment]
@Zanda256 https://github.com/meshery/meshery-cilium/pull/43

**Comment by leecalcote** [comment]
Given #43 has merged are the e2e tests concluded for this adapter? @Revolyssup

**Comment by leecalcote** [comment]
@Revolyssup
