### ISSUE TITLE
[Lifecycle] Install fails with Helm error "name is required"

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-cilium#36]
#### Current Behavior
<img width="445" alt="Screen Shot 2022-03-27 at 9 12 07 AM" src="https://user-images.githubusercontent.com/7570704/160285640-75fe95ea-3737-49a4-9e95-9b562d58a61a.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
@leecalcote regression from dep update (meshkit version)

**Comment by leecalcote** [comment]
@piyushsingariya @Revolyssup please ensure that all adapters running MeshKit v0.5.11 have been properly upgrade with the change to Helm-based provisioning.
