### ISSUE TITLE
[Docs] Readme should include Cilium logo and brief description

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-cilium#4]
**Current State:**
Missing Cilium infö.

**Desired State:**
Copy the formatting of the [meshery-osm readme](https://github.com/meshery/meshery-osm/blob/master/README.md) and include a logo and description of Cilium Service Mesh

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Abhijay007** [comment]
I wanna contribute to this issue, please assign me this issue

**Comment by leecalcote** [comment]
Sounds great, @Abhijay007. Assigning to you now. As I do, knowing that the task is to write a small description (or copy and paste), I'll offer the following grammatical review of your comment above to the extent this review aids in your forthcoming writing on this issue:

> I want to contribute to this issue. Please assign this issue to me.

**Comment by Abhijay007** [comment]
> Sounds great, @Abhijay007. Assigning to you now. As I do, knowing that the task is to write a small description (or copy and paste), I'll offer the following grammatical review of your comment above to the extent this review aids in your forthcoming writing on this issue:
> 
> > I want to contribute to this issue. Please assign this issue to me.

thanks for correcting me, I will keep that in mind !!
