### ISSUE TITLE
[CI] Refresh GitHub workflows

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-cilium#5]
#### Current Behavior
This repo is missing the standard GitHub workflows for Meshery Adapters and needs to be refreshed.

#### Desired Behavior
The meshery-kuma adapter workflows can be copied and reused here.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Abhijay007** [comment]
CI new for me, but I can give it a try, can you please assign me this issue @leecalcote
