### ISSUE TITLE
Update go version in github actions workflows to 1.17

### ISSUE THREAD

**Issue by Zanda256** [meshery/meshery-cilium#51]
#### Current Behavior
Many of places in the workflows still mention go version 1.16 yet the adapters use go version 1.17

#### Desired Behavior
Workflows shouls also use go version 1.17

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by hionnode** [comment]
Can I take this up?

**Comment by MUzairS15** [comment]
@hionnode  Update is required at only one place.
https://github.com/meshery/meshery-cilium/blob/master/.github/workflows/error-ref-publisher.yml

**Comment by leecalcote** [comment]
Hi @hionnode, any luck thus far? Were you in attendance at today's [Meshery Build and Release meeting](https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit), by chance?

**Comment by kethavathsivanaik** [comment]
@leecalcote, @MUzairS15  we can close this issue. It's 1.17 in all files

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshery-cilium/issues/51#issuecomment-1121888150

This needs to be addressed (action version update) , use github version instead of  secrets.

// @leecalcote
