### ISSUE TITLE
[Docs] Reserve adapter port number in Meshery Docs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-cilium#8]
Choose the next sequential number from the Meshery Docs adapters page and reserve the next port number for Cilium Service Mesh. Update Meshery Docs with this port number and main.go in this repo.

**Comment by iamsdas** [comment]
Now that the docs have been updated, @leecalcote could you clarify what you meant by the "update `main.go` in this repo" part? I just have to refer to any other adapter and set up the file with a different adapter name right?

**Comment by leecalcote** [comment]
@iamsdas example here - https://github.com/meshery/meshery-istio/blob/master/main.go
